tap "hivemq/mqtt-cli"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
tap "sambadevi/powerlevel9k"
tap "schniz/tap"
tap "stripe/stripe-cli"
tap "teamookla/speedtest"
brew "ack"
brew "openssl@1.1"
brew "readline"
brew "aircrack-ng", link: false
brew "autoconf"
brew "automake"
brew "coreutils"
brew "libtool"
brew "libyaml"
brew "unixodbc"
brew "asdf"
brew "autojump"
brew "aws-elasticbeanstalk"
brew "bash"
brew "bat"
brew "binutils"
brew "gmp"
brew "binwalk"
brew "bison"
brew "gettext", link: false
brew "certbot"
brew "cifer"
brew "cloc"
brew "cmake"
brew "composer"
brew "cpprestsdk"
brew "gawk"
brew "gnu-sed"
brew "make"
brew "ncurses"
brew "crosstool-ng"
brew "curl"
brew "diff-so-fancy"
brew "doxygen"
brew "entr"
brew "exa"
brew "exiftool"
brew "exiv2"
brew "webp"
brew "ffmpeg"
brew "fop"
brew "fzf"
brew "gdb"
brew "git"
brew "gnupg", link: false
brew "gource"
brew "gperftools"
brew "graphviz"
brew "hashcat"
brew "help2man"
brew "highlight"
brew "htop"
brew "hub"
brew "hugo"
brew "imagemagick"
brew "ios-deploy"
brew "jq"
brew "knock"
brew "lazydocker"
brew "lazygit"
brew "libxslt"
brew "markdown"
brew "mas"
brew "maven"
brew "mitmproxy"
brew "mysql", restart_service: true, link: false
brew "neofetch"
brew "neovim"
brew "ninja"
brew "nmap"
brew "node"
brew "noti"
brew "nvm"
brew "pandoc"
brew "pandoc-citeproc"
brew "pigz"
brew "pkg-config"
brew "postgresql@11", link: true
brew "reattach-to-user-namespace"
brew "ripgrep"
brew "screen"
brew "shellcheck"
brew "shtool"
brew "snort"
brew "stormssh"
brew "telnet"
brew "the_silver_searcher"
brew "tig"
brew "tldr"
brew "tmux"
brew "trash"
brew "tree"
brew "unzip"
brew "vim"
brew "wdiff"
brew "weechat"
brew "wget"
brew "wimlib"
brew "wireshark"
brew "wxmac"
brew "yarn"
brew "youtube-dl"
brew "z"
brew "zlib"
brew "zsh"
brew "hivemq/mqtt-cli/mqtt-cli"
brew "sambadevi/powerlevel9k/powerlevel9k"
brew "schniz/tap/fnm"
brew "stripe/stripe-cli/stripe"
brew "teamookla/speedtest/speedtest"
cask "background-music"
cask "font-sourcecodepro-nerd-font"
cask "kitty"
mas "Adblock Plus", id: 1432731683
mas "Downlink", id: 1454269192
mas "Encrypto", id: 935235287
mas "GarageBand", id: 682658836
mas "Grammarly for Safari", id: 1462114288
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Magnet", id: 441258766
mas "Microsoft Outlook", id: 985367838
mas "Microsoft Word", id: 462054704
mas "Notability", id: 736189492
mas "Numbers", id: 409203825
mas "Ora", id: 1340501510
mas "Pages", id: 409201541
mas "Pocket", id: 568494494
mas "Save to Pocket", id: 1477385213
mas "Spark", id: 1176895641
mas "Termius", id: 1176074088
mas "Xcode", id: 497799835
